export const packages = [
  {
    id: 1,
    title: "Luxury Bali Escape",
    location: "Bali, Indonesia",
    price: 1499,
    duration: "7 Days / 6 Nights",
    type: "Luxury",
    rating: 4.8,
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    badge: "Best Seller",
  },
  {
    id: 2,
    title: "Paris City Lights",
    location: "Paris, France",
    price: 999,
    duration: "5 Days / 4 Nights",
    type: "Romantic",
    rating: 4.6,
    image:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    badge: "Popular",
  },
  {
    id: 3,
    title: "Dubai Adventure",
    location: "Dubai, UAE",
    price: 799,
    duration: "4 Days / 3 Nights",
    type: "Adventure",
    rating: 4.7,
    image:
      "https://images.unsplash.com/photo-1526495124232-a04e1849168c",
    badge: "Hot Deal",
  },
    {
    id: 4,
    title: "Romantic Paris Getaway",
    destination: "Paris, France",
    region: "Europe",
    category: "Romantic",
    image:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    price: 120000,
    discount: 15,
    duration: "5 Nights / 6 Days",
    rating: 4.8,
    inclusions: ["Flights", "Hotel", "Sightseeing", "Breakfast"],
     badge: "Popular",
    highlights: [
      "Eiffel Tower visit",
      "Seine River Cruise",
      "City Night Tour",
    ],
  },
  {
    id: 5,
    title: "Bali Adventure Escape",
    destination: "Bali, Indonesia",
    region: "Asia",
    category: "Adventure",
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 78000,
    discount: 10,
    duration: "6 Nights / 7 Days",
    rating: 4.7,
    inclusions: ["Resort Stay", "Local Transport", "Guided Tours"],
     badge: "Popular",
    highlights: [
      "Ubud Jungle Trek",
      "Water Sports",
      "Beachside Resort",
    ],
  },
  {
    id: 6,
    title: "Luxury Dubai Experience",
    destination: "Dubai, UAE",
    region: "Middle East",
    category: "Luxury",
    image:
      "https://images.unsplash.com/photo-1498496294664-d9372eb521f3",
    price: 95000,
    discount: 20,
    duration: "4 Nights / 5 Days",
    rating: 4.6,
    inclusions: ["5⭐ Hotel", "Desert Safari", "Airport Transfers"],
     badge: "Popular",
    highlights: [
      "Burj Khalifa",
      "Luxury Shopping",
      "Desert Safari",
    ],
  },
  {
    id: 7,
    title: "Maldives Honeymoon Special",
    destination: "Maldives",
    region: "Asia",
    category: "Romantic",
    image:
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21",
    price: 150000,
    discount: 18,
    duration: "5 Nights / 6 Days",
    rating: 4.9,
    inclusions: ["Overwater Villa", "All Meals", "Speedboat Transfer"],
     badge: "Popular",
    highlights: [
      "Private Beach",
      "Sunset Cruise",
      "Snorkeling",
    ],
  },
  {
    id: 8,
    title: "Tokyo Cultural Discovery",
    destination: "Tokyo, Japan",
    region: "Asia",
    category: "Cultural",
    image:
      "https://images.unsplash.com/photo-1549693578-d683be217e58",
    price: 130000,
    discount: 10,
    duration: "7 Nights / 8 Days",
    rating: 4.8,
    inclusions: ["Hotels", "Metro Pass", "Guided Tours"],
     badge: "Popular",
    highlights: [
      "Mount Fuji Day Trip",
      "Cherry Blossom Spots",
      "Anime Districts",
    ],
  },
];
